-- Superseded by 0019_remove_peliculas_planilhas_financeiro_bancario.sql —
-- a aba Planilhas (e a tabela sheet_links) foi removida. Conteúdo original
-- (ALTER TABLE sheet_links ADD COLUMN allowed_sector_ids/allowed_user_ids)
-- não se aplica mais; mantido como no-op pra não quebrar o replay idempotente
-- de migrations em bancos antigos.
