-- Superseded by 0019_remove_peliculas_planilhas_financeiro_bancario.sql —
-- finance_audit_log era exclusiva do módulo Financeiro Bancário, removido.
-- Mantido como no-op pra não quebrar o replay idempotente de migrations.
