import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import sectorsRouter from "./sectors";
import queueRouter from "./queue";
import adminRouter from "./admin";
import webhookRouter from "./webhook";
import crmRouter from "./crm";
import chatRouter from "./chat";
import whatsappProxyRouter from "./whatsapp";
import internalChatRouter from "./internalChat";
import tasksRouter from "./tasks";
import settingsRouter from "./settings";
import partnerLinksRouter from "./partnerLinks";
import tradeInRouter from "./tradeIn";
import trainingsRouter, { enforceMandatoryTrainings } from "./trainings";
import rhRouter from "./rh";
import rhDpRouter, { enforceMandatoryClockIn } from "./rhDp";
import rafflesRouter from "./raffles";
import botRouter from "./bot";
import financeRouter from "./finance";
import financePaymentsRouter from "./financePayments";
import documentsRouter from "./documents";
import meetingsRouter from "./meetings";
import storesRouter from "./stores";
import resultsRouter from "./results";
import relatoriosRouter from "./relatorios";
import superadminRouter from "./superadmin";
import superadminSaasRouter from "./superadminSaas";
import systemBoardRouter from "./systemBoard";
import teamDirectoryRouter from "./teamDirectory";
import ticketsRouter from "./tickets";
import tvboxRouter from "./tvbox";
import pdfRouter from "./pdf";
import rotinasRouter, { enforceMandatoryRoutines } from "./rotinas";
import catalogRouter, { catalogPublicRouter } from "./catalog";
import promoGalleryRouter from "./promoGallery";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(superadminRouter);
router.use(superadminSaasRouter);
// Trava o sistema (423) enquanto houver treinamento (ou checklist, que agora
// é só um tipo de treinamento — ver trainings.ts) obrigatório pendente.
router.use(enforceMandatoryTrainings);
router.use(enforceMandatoryClockIn);
router.use(enforceMandatoryRoutines);
router.use(sectorsRouter);
router.use(queueRouter);
router.use(adminRouter);
router.use(webhookRouter);
router.use(crmRouter);
router.use(chatRouter);
router.use(whatsappProxyRouter);
router.use(internalChatRouter);
router.use(tasksRouter);
router.use(settingsRouter);
router.use(partnerLinksRouter);
router.use(tradeInRouter);
router.use(trainingsRouter);
router.use(rhRouter);
router.use(rhDpRouter);
router.use(rafflesRouter);
router.use(botRouter);
router.use(financeRouter);
router.use(financePaymentsRouter);
router.use(documentsRouter);
router.use(meetingsRouter);
router.use(storesRouter);
router.use(resultsRouter);
router.use(relatoriosRouter);
router.use(systemBoardRouter);
router.use(teamDirectoryRouter);
router.use(ticketsRouter);
router.use(tvboxRouter);
router.use(pdfRouter);
router.use(rotinasRouter);
router.use(catalogRouter);
// Sem requireAuth: a vitrine pública é vista por clientes sem login.
router.use(catalogPublicRouter);
router.use(promoGalleryRouter);

export default router;
